name: Automatic Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  automatic-release:
    name: Create GitHub Release automatically
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version without leading v
        id: extract_version
        run: |
          version=$(echo "${{ github.ref_name}}" | sed 's/^v//')
          echo "Version: $version"
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2.5.0
        with:
          name: Version ${{ steps.extract_version.outputs.version }}
          body: |
            Automated release for version ${{ steps.extract_version.outputs.version }}
